[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.http_checks]]
    method = "GET"
    path = "/"
    protocol = "http"

  [[services.ports]]
    handlers = ["http"]
    port = 80
